<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('jobs', ['as'=> 'jobs.index', 'uses' => 'JobController@index']);
Route::post('jobs', ['as'=> 'jobs.store', 'uses' => 'JobController@store']);
Route::get('jobs/create', ['as'=> 'jobs.create', 'uses' => 'JobController@create']);
Route::put('jobs/{jobs}', ['as'=> 'jobs.update', 'uses' => 'JobController@update']);
Route::patch('jobs/{jobs}', ['as'=> 'jobs.update', 'uses' => 'JobController@update']);
Route::get('jobs/{id}/delete', array('as' => 'jobs.delete', 'uses' => 'JobController@getDelete'));
Route::get('jobs/{id}/confirm-delete', array('as' => 'jobs.confirm-delete', 'uses' => 'JobController@getModalDelete'));
Route::get('jobs/{jobs}', ['as'=> 'jobs.show', 'uses' => 'JobController@show']);
Route::get('jobs/{jobs}/edit', ['as'=> 'jobs.edit', 'uses' => 'JobController@edit']);

});


Route::group(array('prefix' => 'admin/customer/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customer.'), function () {

	Route::get('customers', ['as'=> 'customers.index', 'uses' => 'Customer\CustomerController@index']);
	Route::post('customers', ['as'=> 'customers.store', 'uses' => 'Customer\CustomerController@store']);
	Route::get('customers/create', ['as'=> 'customers.create', 'uses' => 'Customer\CustomerController@create']);
	Route::put('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
	Route::patch('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
	Route::get('customers/{id}/delete', array('as' => 'customers.delete', 'uses' => 'Customer\CustomerController@getDelete'));
	Route::get('customers/{id}/confirm-delete', array('as' => 'customers.confirm-delete', 'uses' => 'Customer\CustomerController@getModalDelete'));
	Route::get('customers/{customers}', ['as'=> 'customers.show', 'uses' => 'Customer\CustomerController@show']);
	Route::get('customers/{customers}/edit', ['as'=> 'customers.edit', 'uses' => 'Customer\CustomerController@edit']);

});
